console-logging: false
#Create your tasks in the below section using this format.
##Intervals are in seconds
##If allplayers is true, the task will be done for every online player
##Commands are executed from top to bottom
tasks:
 sampletask:
     interval: 40
     allplayers: false
     commands:
      - say Hello World
      - say Hello Again
 sampletask2:
     interval: 20
     allplayers: true
     commands:
      - say hello @p